import Head from 'next/head';
import About from '../Components/About';
import Banner from '../Components/Banner';
import Footer from '../Components/Footer';
import Navigation from '../Components/Navigation';
import Projects from '../Components/Projects';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Daniel Olasehinde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.svg" />
      </Head>
      <Navigation />
      {/* <Banner />
      <Projects />
      <About />
      <Footer /> */}
    </div>
  );
}
